/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

const API_CACHE_VERSION = 'v3';
 add .API_CACHE_VERSION

clientsClaim();
self.skipWaiting();

// Ensure offline fallback page is cached during install
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open('offline-cache').then((cache) => cache.addAll(['/offline.html', process.env.PUBLIC_URL + '/index.html']).catch(() => {}))
  );
});

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.


/*self.addEventListener('fetch', (event) => {
  const { request } = event;

  if(request.url.includes('/api/data')) {
    event.respondWith(
      caches.open(API_CACHE_NAME).then(async (cache) => {
        try {
          const response = await fetch(request);
          cache.put(request, response.clone());
          return response;
        } catch (err) {
          const cached = await cache.match(request);
          if (cached) return cached;

          // Optional fallback if cache is empty
          return new Response(
            JSON.stringify({ error: 'Network unavailable' }),
            { headers: { 'Content-Type': 'application/json' }, status: 503 }
          );
        }
      })
    );
  }
});*/

// Runtime caching for API responses: cache GET requests to /api/products
self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Only handle GET API requests to our backend for products
  if (request.method === 'GET' && request.url.includes('/api/products')) {
    event.respondWith((async () => {
      // Two-stage cache strategy: api-cache-0 (initial), api-cache-1 (promoted)
      const cache0 = 'api-cache-v0';
      const cache1 = 'api-cache-   v1';

      const keys = await caches.keys();
      const hasCache1 = keys.includes(cache1);

      const fetchAndCache = async (cacheName) => {
        const response = await fetch(request);
        const cache = await caches.open(cacheName);
        cache.put(request, response.clone());
        return response;
      };

      // If cache1 exists, use network-first updating cache1
      if (hasCache1) {
        try {
          const resp = await fetchAndCache(cache1);
          console.log('[SW] Updated api-cache-1 for', request.url);
          return resp;
        } catch (err) {
          const cached = await caches.open(cache1).then(c => c.match(request));
          if (cached) {
            console.log('[SW] Serving api-cache-1 for', request.url);
            return cached;
          }
          console.log('[SW] No cache1 available and network failed for', request.url);
          return new Response(JSON.stringify({ error: 'Network unavailable' }), { headers: { 'Content-Type': 'application/json' }, status: 503 });
        }
      }

      // If only cache0 exists, try network and promote to cache1; else serve cache0
      const hasCache0 = keys.includes(cache0);
      if (hasCache0) {
        try {
          const resp = await fetchAndCache(cache1);
          console.log('[SW] Promoted api-cache-0 -> api-cache-1 for', request.url);
          // promote: delete cache0
          try { await caches.delete(cache0); } catch (e) {}
          return resp;
        } catch (err) {
          const cached = await caches.open(cache0).then(c => c.match(request));
          if (cached) {
            console.log('[SW] Serving api-cache-0 (promotion pending) for', request.url);
            return cached;
          }
          console.log('[SW] No cache0 available and network failed for', request.url);
          return new Response(JSON.stringify({ error: 'Network unavailable' }), { headers: { 'Content-Type': 'application/json' }, status: 503 });
        }
      }

      // No caches yet: fetch and store in cache0 (initial cache)
      try {
        const r = await fetchAndCache(cache0);
        console.log('[SW] Wrote initial api-cache-0 for', request.url);
        return r;
      } catch (err) {
        console.log('[SW] Network failed and no caches exist for', request.url);
        return new Response(JSON.stringify({ error: 'Network unavailable' }), { headers: { 'Content-Type': 'application/json' }, status: 503 });
      }
    })());
    return;
  }

  // Fallback for navigation requests: if navigation fails (offline) return offline page
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(async () => {
        const cache = await caches.open('offline-cache');
        const cached = await cache.match('/offline.html');
        return cached || caches.match(process.env.PUBLIC_URL + '/index.html');
      })
    );
  }
});

self.addEventListener('activate', (event) => {
  const keep = ['api-cache-0', 'api-cache-1', 'images', 'offline-cache'];

  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.map((key) => {
          // Keep workbox precache and runtime caches, and our keep list
          if (key.startsWith('workbox') || keep.includes(key)) return null;
          // Otherwise delete old api-cache variants or stale caches
          return caches.delete(key);
        })
      )
    )
  );
});